# Generated by Django 3.1.1 on 2020-10-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
# the "initial migrations" for an app are the migrations that creates the first version of that app's tables.
# if we make changes in the model and run migrate command then this initial = true will be lost.
    dependencies = [
    ]
# dependencies are the list of items on which the migrations files are depends.
# migration files are below operations.

    operations = [
        migrations.CreateModel(
            name='data_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.TextField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.TextField(max_length=20)),
                ('Confirm_Password', models.TextField(max_length=20)),
            ],
        ),
    ]
# operations is list of the all operations on models.