# Generated by Django 3.1.1 on 2020-10-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_register',
            name='images',
            field=models.ImageField(default='hiiiiii', upload_to='media'),
        ),
    ]
