# Generated by Django 3.1.1 on 2020-10-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0002_data_register_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_register',
            name='images',
        ),
    ]
