# Generated by Django 3.1.1 on 2020-11-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0003_remove_data_register_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_register',
            name='adhar_card',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='data_register',
            name='pancard',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='data_register',
            name='profile_photo',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
