# Generated by Django 3.1.1 on 2020-11-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0004_auto_20201102_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_register',
            name='adhar_card',
            field=models.ImageField(default=0, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='data_register',
            name='pancard',
            field=models.ImageField(default=0, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='data_register',
            name='profile_photo',
            field=models.ImageField(default=0, upload_to='profile'),
        ),
    ]
