# Generated by Django 3.1.1 on 2020-11-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0005_auto_20201102_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_register',
            name='adhar_card',
            field=models.FileField(default=0, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='data_register',
            name='pancard',
            field=models.FileField(default=0, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='data_register',
            name='profile_photo',
            field=models.FileField(default=0, upload_to='profile'),
        ),
    ]
