# Generated by Django 3.1.3 on 2020-12-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0007_answers_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.URLField(blank=True, null=True),
        ),
    ]
