# Generated by Django 3.1.3 on 2020-12-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0008_auto_20201207_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
