# Generated by Django 3.1.3 on 2020-12-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0010_answers_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
